#if !NET
#define PLATFORM_IDENTIFIED

using WhiteCane.Platforms;
#endif

namespace WhiteCane;

public static class WhiteCane
{
    /// <summary>
    /// Initializes the WhiteCane Library
    /// </summary>
    /// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
    /// <returns></returns>
    public static MauiAppBuilder UseWhiteCane(this MauiAppBuilder builder)
    {
#if PLATFORM_IDENTIFIED
        builder.InitializePlatform();
#endif
        return builder;
    }
}
