// <auto-generated/>
using System.Collections.ObjectModel;

namespace WhiteCane.Samples
{
    public static class Routes
    {
        public const string AccessibilityContentViewPage = "AccessibilityContentViewPage";
        public const string HomePage = "HomePage";
        public const string BasePage = "BasePage";
    
        private static List<string> allRoutes = new()
        {
            AccessibilityContentViewPage,
            HomePage,
            BasePage
        };
        
        public static ReadOnlyCollection<string> AllRoutes => allRoutes.AsReadOnly();
        
        private static Dictionary<string, Type> routeTypeMap = new()
        {
            {AccessibilityContentViewPage,typeof(Features.AccessibilityContentViewPage)},
            {HomePage,typeof(Features.HomePage)},
            {BasePage,typeof(Features.BasePage)}
        };
        
        public static ReadOnlyDictionary<string, Type> RouteTypeMap => routeTypeMap.AsReadOnly();
    }
}